/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   export-form.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-toast/paper-toast.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../iron-form/iron-form.d.ts" />
/// <reference path="../paper-checkbox/paper-checkbox.d.ts" />
/// <reference path="../paper-dropdown-menu/paper-dropdown-menu.d.ts" />
/// <reference path="../paper-listbox/paper-listbox.d.ts" />
/// <reference path="../paper-item/paper-icon-item.d.ts" />
/// <reference path="../iron-icon/iron-icon.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../paper-spinner/paper-spinner.d.ts" />

declare namespace UiElements {

  /**
   * Export data form with export flow logic.
   *
   * Provides the UI and and logic to export data from the data store to `destination`
   * export method provider. It uses events API to communicate with other elements.
   *
   * Required elements to be present in the DOM:
   *
   * -   `arc-data-export` - getting data from the datastore
   * -   element that handles `file-data-save` event
   * -   element that handles `google-drive-data-save` event
   *
   * ### Example
   *
   * ```html
   * <arc-data-export app-version="12.0.0" electron-cookies></arc-data-export>
   * <google-drive-upload></google-drive-upload>
   * <file-save></file-save>
   *
   * <export-panel></export-panel>
   * ```
   *
   * ### Styling
   *
   * `<export-panel>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--export-panel` | Mixin applied to the element | `{}`
   * `--error-toast` | Mixin applied to the error toast message | `{}`
   * `--warning-primary-color` | Error toast background color | `#FF7043`
   * `--warning-contrast-color` | Error toast color | `#fff`
   * `--arc-font-headline` | Mixin applied to the header | `{}`
   */
  class ExportForm extends Polymer.Element {

    /**
     * Export destination:
     * - 0 - to file
     * - 1 - to Google Drive
     */
    destination: number|null|undefined;

    /**
     * When `true` the component began export flow.
     */
    readonly loading: boolean|null|undefined;

    /**
     * When set this value will be used for export file name.
     */
    fileName: string|null|undefined;

    /**
     * Handler for click event. Calls `startExport()` function.
     */
    _prepare(): void;

    /**
     * Uses currend form data to start export flow.
     * This function is to expose public API to export data.
     *
     * @returns A promise resolved when export finishes
     */
    startExport(): Promise<any>|null;
    _getExportFileName(): any;
  }
}

interface HTMLElementTagNameMap {
  "export-form": UiElements.ExportForm;
}
